#cloud-config
users:
  - name: web
    primary_group: web
    groups: wheel
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC35OstdMUOWrBwchYucn7J0hybPt5mymi3vrlutK4F2 csethcampbell@gmail.com
package_update: true
package_upgrade: true
packages:
  - nginx
  - nmap
